<?php
if (!defined('IN_IDEACMS')) exit();

/**
 * 用户权限配置信息
 */
return array (
  1 => 
  array (
    0 => 'index',
    1 => 'auth',
    2 => 'category',
    3 => 'content',
    4 => 'model',
    5 => 'user',
    6 => 'position',
    7 => 'linkage',
    8 => 'plugin',
    9 => 'attachment',
    10 => 'relatedlink',
    11 => 'block',
    12 => 'member',
    13 => 'theme',
    14 => 'html',
    15 => 'form',
    16 => 'tag',
    17 => 'ip',
    18 => 'site',
  ),
  2 => 
  array (
    0 => 'index-index',
    1 => 'index-config',
    2 => 'index-cache',
    3 => 'index-log',
    4 => 'index-clearlog',
    5 => 'index-updatemap',
    6 => 'model-index',
    7 => 'model-add',
    8 => 'model-edit',
    9 => 'model-del',
    10 => 'model-import',
    11 => 'model-export',
    12 => 'model-cdisabled',
    13 => 'model-fields',
    14 => 'model-addfield',
    15 => 'model-editfield',
    16 => 'model-delfield',
    17 => 'model-disable',
    18 => 'model-cache',
    19 => 'category-index',
    20 => 'category-add',
    21 => 'category-edit',
    22 => 'category-del',
    23 => 'category-cache',
    24 => 'content-index',
    25 => 'content-add',
    26 => 'content-del',
    27 => 'content-updateurl',
    28 => 'position-index',
    29 => 'position-add',
    30 => 'position-edit',
    31 => 'position-del',
    32 => 'position-list',
    33 => 'position-adddata',
    34 => 'position-editdata',
    35 => 'position-deldata',
    36 => 'position-cache',
    37 => 'plugin-index',
    38 => 'plugin-set',
    39 => 'plugin-disable',
    40 => 'plugin-del',
    41 => 'plugin-add',
    42 => 'attachment-index',
    43 => 'attachment-del',
    44 => 'relatedlink-index',
    45 => 'relatedlink-add',
    46 => 'relatedlink-edit',
    47 => 'relatedlink-del',
    48 => 'relatedlink-import',
    49 => 'html-index',
    50 => 'html-category',
    51 => 'html-clear',
    52 => 'form-index',
    53 => 'form-list',
    54 => 'form-add',
    55 => 'form-edit',
    56 => 'form-del',
  ),
  3 => 
  array (
    0 => 'index-config',
    1 => 'auth-add',
    2 => 'auth-edit',
    3 => 'form-list',
    4 => 'form-config',
  ),
);